import type { Metadata } from "next";
import "./globals.css";
import TopHeader from "@/components/Landing/TopHeader";
import Header from "@/components/Landing/Header";

export const metadata: Metadata = {
  title: "Anton Ai",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <TopHeader />
        <Header />
        {children}
      </body>
    </html>
  );
}
